package id.co.beton.saleslogistic_trackingsystem.Configuration;

import id.co.beton.saleslogistic_trackingsystem.BuildConfig;

/**
 * Class Constans
 */
public class Constants {
    public static final String API_SERVER_ADDR = BuildConfig.BASE_URL;
    public static final boolean DEBUG = BuildConfig.DEBUG;
    public static final boolean DEV_MODE = false;
    public static final boolean IS_CHECK_FAKE_GPS = true;
    public static final String USER_EMAIL = "email";
    public static final String USERNAME = "username";
    public static final String NAME = "name";
    public static final String NIP = "nip";
    public static final String PHONE = "phone";
    public static final String LAST_LOGIN = "last_login";
    public static final String USER_TOKEN = "token_key";
    public static final String JWTACCESSTOKEN = "jwt_access_token";
    public static final String USER_ID = "id";
    public static final String USER_ROLE = "user_role";
    public static final String STATUS_BREAK_TIME = "status_break_time";
    public static final String STATUS_ALL_SERVICE_RUNNING = "status_all_service";
    public static final String STATUS_OUT_OFFICE = "status_out_office";
    public static final String STATUS_IN_OFFICE = "status_in_office";
    public static final String CURRENT_PAGE_PLAN = "current_page_plan";
    public static final String TAP_OUT_TIMEOUT = "tap_out_timeout_time";
    public static final int LIMIT_REQUEST = 5;
    public static final String API_GOOGLE_MAP = "AIzaSyAEkUYTl18iko3Q0EgAKCthMLY-637KYXI"; //"AIzaSyD4X-4HiLdrfwJYZPFxHbqHfwUUUvlOIrc";//AIzaSyCGF41kbZX7jC3IXOGhpB4Xake9Rpk-_YA
    // digunakan untuk session perpindahan state
    public static final String USER_SESSION = "customer_name";
    public static final String STATUS_CONFIRM_INVOICE = "status_confirm_invoice";

    // filename Logo
    public static final String FILENAME_LOGO = "_LOGO_COMPANY.jpg";

    // Language
    public static final String MAPS_LANGUAGE = "id";

    //constant for break time
    public static final String DATA_TIME = "data";
    public static final String SECONDS = "seconds";
    public static final String TIME = "time";

    //constanct for visit plan
    public static final String PLAN_ID = "plan_id";
    public static final String NFC_CODE = "nfc_code";
    public static final String NFC_CODE_ROUTE = "nfc_code_route";
    public static final String INVOICE_SIZE = "invoice_size";
    public static final String PACKING_SLIP_SIZE = "packing_slip_size";
    // additional variable for custom visit plan, generated by sales it self
    public static final String CUSTOM_PLAN = "custom_plan";

    //branch
    public static final String BRANCH_ID = "branch_id";
    public static final String DIVISION_ID = "division_id";
    public static final String MAX_UNLOADING = "max_length_unloading";
    public static final String ADDITIONAL_TIME_PERMISSION = "additional_time";
    public static final String MAX_VISIT_TIME = "max_length_visit_time";
    public static final String MAX_IDLE_TIME = "max_idle_time";
    public static final String RES_TIME = "rest_time"; //max_breaktime_time
    public static final String LONG_BRAEK_TIME = "long_break_time"; //lama waktu istirahat
    public static final String START_VISIT = "start_visit";
    public static final String END_VISIT = "end_visit";
    public static final String START_UNLOADING = "start_unloading";
    public static final String END_UNLOADING = "end_unloading";
    public static final String LAST_LAT = "last_lat";
    public static final String LAST_LNG = "last_lng";
    public static final String TIME_LAST_POSITION = "time_last_position";
    public static final String START_VISIT_TIME_SERVICE = "start_visit_time_service";
    public static final String STATUS_CHECKIN_BRANCH = "status_checkin_branch";
    public static final String STATUS_CHECKOUT_BRANCH = "status_checkout_branch";

    public static final String ROLE_SALES = "sales";
    public static final String ROLE_DRIVER = "logistic";

    //data for check salah jalur
    public static final String LAT_START = "lat_start";
    public static final String LNG_START = "lng_start";
    public static final String LAT_MIDLE = "lat_midle";
    public static final String LNG_MIDLE = "lng_midle";
    public static final String LAT_END = "lat_end";
    public static final String LNG_END = "lng_end";

    public static final String INDEX_AKTIF = "index_aktif";
    public static final String START_LAT_CUSTOMER = "lat_customer";
    public static final String START_LNG_CUSTOMER = "lng_customer";

    public static final String LAT_OFFICE = "lat_office";
    public static final String LNG_OFFICE = "lngt_office";
    public static final String NFC_CODE_OFFICE = "nfc_code_office";

    public static final String LAT_OFFICE_START = "lat_office_start";
    public static final String LNG_OFFICE_START = "lngt_office_start";
    public static final String NFC_CODE_OFFICE_START = "nfc_code_office_start";

    public static final String LAT_OFFICE_END = "lat_office_end";
    public static final String LNG_OFFICE_END = "lngt_office_end";
    public static final String NFC_CODE_OFFICE_END = "nfc_code_office_end";

    public static final String LAT_CUSTOM_OFFICE_START = "lat_custom_office_start";
    public static final String LNG_CUSTOM_OFFICE_START = "lng_custom_office_start";
    public static final String ADDRESS_CUSTOM_OFFICE_START = "address_custom_office_start";

    public static final String LAT_CUSTOM_OFFICE_END = "lat_custom_office_end";
    public static final String LNG_CUSTOM_OFFICE_END = "lng_custom_office_end";
    public static final String ADDRESS_CUSTOM_OFFICE_END = "address_custom_office_end";

    public static final int TOLERANSI_JARAK = 100; //satuan meter
    public static final String STATUS_STOP_SERVIE_IDLE_TIME = "status_stop_service_idle_time";

    public static final String START_VISIT_CUSTOMER = "start_visit_customer";
    public static final int MIN_VISIT_CUSTOMER = 60; //satuan detik
    public static final int TAP_OUT_TIME_TIMEOUT = 5; //satuan detik

    public static final int MAX_SIZE_IMAGE = 700;
    public static final int MAX_SIZE_QUALITY_IMAGE = 100;
    public static final int TOTAL_PRINT = 2;

    public static final int MAX_COUNT_IMAGE = 3;
    public static final int MAX_COUNT_IMAGE_MEMO = 10;

    // constant for alert
    public static final String ALERT_WRONG_ROUTE = "alert_wrong_route";
    public static final String ALERT_BREAK_TIME = "alert_break_time";
    public static final String IS_USING_ROUTE = "is_using_route";
    public static final int MIN_BATTERY_PERCENTAGE_ALERT = 10;

    // constant for collector
    public static final String IS_COLLECTOR_ONLY = "is_collector_only";
    public static final String IS_CAN_COLLECT = "is_can_collect";

    // constant for calculate distance
    public static final String ODOMETER = "odometer";
    public static final String DISTANCE_POINT = "distance_point";
    public static final String DUMP_DISTANCE = "dump_distance";
    public static final String LAST_LAT_DISTANCE = "last_lat_distance";
    public static final String LAST_LNG_DISTANCE = "last_lng_distance";
    public static final String LAST_CHECKIN = "last_checkin";

    // asset
    public static final String ASSET_CODE = "asset_code";
    public static final String ASSET_NAME = "asset_name";

    // list destination
    public static final String LIST_DESTINATION = "list_destination";
    public static final String LIST_VISITED_CUSTOMER = "list_visited_customer";

    public static final int VIBRATE_DURATION = 1000; //ms

    public static final String TERM_AND_CONDITION_TITLE = "SYARAT & KETENTUAN:";
    public static final String TERM_AND_CONDITION_BODY = "Pembayaran yang menggunakan cek atau giro bank dianggap sah bila telah cair di bank penerima. Terima kasih.";

    //custom function
    public static final String APPS = "apps";
    public static final String API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE1NzQwNjUwODQsImV4cCI6MTU3NDY2OTg4NCwiaWRlbnRpdHkiOjEsImlhdCI6MTU3NDA2NTA4NH0.pC9h5aOYLjhq7FX_XxIV-MOfhwOG3zUfwjcln35qCdY";
}
